### ISSUE TITLE
Concern about the code line

### ISSUE THREAD

**Issue by arthef** [tigase/k8s-scripts#10]
https://github.com/tigase/k8s-scripts/blob/00da2f4bb6d6bbe20dfeecdfb19cbab97b4814c3/scripts/cluster-ingress-nginx.sh#L28

I am not sure if this line is correct and inserts correct data in a correct place.

Could it be replaced with line:
```
yq e -i '.spec.tcp = []' "${CL_DIR}/${NAME}/${NAME}.yaml"
```
This could give us more consistent results in case, the default content of the file changes.

**Comment by hantu85** [comment]
Actually proposed solution is incorrect. It would add a list/array as a `tcp` field in `spec` section. The current solution with `sed` adds a `tcp` field in a `values` section in `spec` section but as a map/object.

This empty map/object is required as later on scripts like `cluster-onedev.sh` are using `sed` to to add entries to this map, see https://github.com/tigase/k8s-scripts/blob/00da2f4bb6d6bbe20dfeecdfb19cbab97b4814c3/scripts/cluster-onedev.sh#L155

This is required as it we need to use `!!str` before added key to the YAML file, as without it `helm-controller` from fluxcd fails, see https://github.com/fluxcd/helm-controller/issues/296. Due to that, it is impossible to add this port specification using `yq` and we are forced to use `sed` anyway due to `helm-controller` bug.

**Comment by arthef** [comment]
My first concern was that after the original sed command in [cluster-ingress-nginx.sh](https://github.com/tigase/k8s-scripts/blob/00da2f4bb6d6bbe20dfeecdfb19cbab97b4814c3/scripts/cluster-ingress-nginx.sh#L28) line, the "upgrade" element lost indentation.

Ok, I now understand the problem. It seems like `yq` does not allow to add key in form of '!!str num'. I tried different tricks with no luck.

So, what about this. We could first run command like this:
```shell
yq e '.spec.values.tcp.str_22 = "abc/def:22"' -i file.yaml
```
And then run sed to "correct" it:
```shell
sed -ie "s/str_22/\!\!str 22/" file.yaml
```
This would ensure all indentations are correct and preserved and would have the least impact on the yaml file content.

Perhaps we would not need the empty tcp object in ingress-nginx.yaml as the port spec could be added later.

What do you think?

**Comment by hantu85** [comment]
This trick will not work. The issue is that not only `cluster-onedev.sh` adds those entries, but also a script for setting up Tigase (for other ports). The issue is that each call to `yq` replaces `!!str 22` with `22`, so even if we would replace `str_22` with `!!str 22` in onedev setup script, Tigase setup script will call `yq` and replace `!!str 22` with `22` which will cause the issue. 

Due to that usage of `yq` is not possible (or at least I was not able to use it).

**Comment by arthef** [comment]
I thought so too but I tested it before adding my comment. Unless I missed something this seems to be working correctly:
```shell
$ grep str ingress-nginx.yaml 
$ yq e '.spec.values.tcp.str_22 = "abc/def:22"' -i ingress-nginx.yaml 
$ grep str ingress-nginx.yaml 
      str_22: abc/def:22
$ sed -ie "s/str_22/\!\!str 22/" ingress-nginx.yaml
$ grep str ingress-nginx.yaml 
      !!str 22: abc/def:22
$ yq e '.spec.values.tcp.str_33 = "abc/def:22"' -i ingress-nginx.yaml 
$ grep str ingress-nginx.yaml 
      !!str 22: abc/def:22
      str_33: abc/def:22
$ sed -ie "s/str_33/\!\!str 33/" ingress-nginx.yaml
$ grep str ingress-nginx.yaml 
      !!str 22: abc/def:22
      !!str 33: abc/def:22
$ 
$ yq --version
yq (https://github.com/mikefarah/yq/) version 4.16.1
```

**Comment by hantu85** [comment]
I've rechecked and now it works. I've modified scripts by creating port forwarding function and using it for generating port fowarding

**Comment by arthef** [comment]
In such a case do we still need the line in `cluster-ingress-nginx.sh` script?

**Comment by hantu85** [comment]
It is no longer needed. I've just removed it.

**Comment by arthef** [comment]
Thank you.
